prepare:
  fetch:
  - url: https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/.rubocop_base.yml
    path: ".rubocop_base.yml"
  - url: https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/.rubocop_cc_base.yml
    path: ".rubocop_cc_base.yml"
  - url: https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/styles/base.yml
    path: styles/base.yml
  - url: https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/styles/cc_base.yml
    path: styles/cc_base.yml
plugins:
  rubocop:
    enabled: true
    config: ".rubocop_cc.yml"
    channel: rubocop-0-82
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: false
    channel: eslint-3
  fixme:
    enabled: false
  markdownlint:
    enabled: false
exclude_patterns:
- ".git/"
- "**.xml"
- "**.yaml"
- "**.yml"
- locale/
- spec/
- tools/
- test/
- lib/VMwareWebService/wsdl41/
version: '2'
