cache: bundler
language: ruby
rvm:
  - 2.5.8
  - 2.6.6
before_install: gem install bundler -v 1.14.4
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/a15a36fcd1750318ad5f
    on_success: change
    on_failure: always
    on_start: never
